
baseURL = "/"
languageCode = "en-us"
title = "Kerem Yıldırır"
theme = "notrack"
newContentEditor = "emacs"
mainSections = ["Home"]

# disqusShortname = "example"
paginate = 5
ignoreErrors = ["error-remote-getjson"]
[params]
  author = "Kerem Yildirir"
  siteHeading = "Kerem Yıldırır" # defaults to author
  showBlogLatest = false
  mainSections = ["projects"]
  showTaxonomyLinks = false
  nBlogLatest = 3 # number of blog post om the home page
  blogLatestHeading = "My Projects"
  color_theme = "coffee"
  [params.social]
    github = "keremyldrr"
    linkedin = "kerem-yildirir-75b070145/"
    email = "kerem.yildirir@tum.de"
    researchgate = "Kerem_Yildirir"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
